Bump version to 0.9.1. 1. Move all temporary data to /var/tmp/wrtbwmon. 2. Optimizate some logic. 3. Using renamefile function to get the filename of ipv6 and total traffic datas.
Signed-off-by: Van Waholtz <vanwaholtz@gmail.com>

diff --git a/net/usr/sbin/wrtbwmon b/net/usr/sbin/wrtbwmon
--- a/net/usr/sbin/wrtbwmon
+++ b/net/usr/sbin/wrtbwmon
@@ -10,6 +10,7 @@ updatePID=
 logFile=/var/log/wrtbwmon.log
 lockFile=/var/lock/wrtbwmon.lock
 pidFile=/var/run/wrtbwmon.pid
+tmpDir=/var/tmp/wrtbwmon
 
 # Debug parameters for readDB.awk.
 mode=
@@ -54,7 +55,7 @@ checkDB()
 
 checkWAN()
 {
-	[ -z "$wan" ] && echo "Warning: failed to detect WAN interface."
+	[ -z "$1" ] && echo "Warning: failed to detect WAN interface."
 }
 
 lookup()
@@ -140,7 +141,7 @@ lockFunc()
 	local flag=0
 
 	while [ "$flag" = 0 ]; do
-		local tempfile=$(mktemp /tmp/lock.XXXXXX)
+		local tempfile=$(mktemp $tmpDir/lock.XXXXXX)
 		ln $tempfile $lockFile >/dev/null 2>&1 && flag=1
 		rm $tempfile
 
@@ -207,26 +208,31 @@ publish()
 {
 	# sort DB
 	# busybox sort truncates numbers to 32 bits
-	grep -v '^#' $DB | awk -F, '{OFS=","; a=sprintf("%f",$4/1e6); $4=""; print a,$0}' | tr -s ',' | sort -rn | awk -F, '{OFS=",";$1=sprintf("%f",$1*1e6);print}' > /tmp/sorted_${updatePID}.tmp
+	grep -v '^#' $DB | awk -F, '{OFS=","; a=sprintf("%f",$6/1e6); $6=""; print a,$0}' | tr -s ',' | sort -rn | awk -F, '{OFS=",";$1=sprintf("%f",$1*1e6);print}' > $tmpDir/sorted_${updatePID}.tmp
 
 	# create HTML page
-	rm -f ${pb_html}.tmp
-	cp $dataDir/usage.htm1 ${pb_html}.tmp
+	local htmPage="$tmpDir/${pb_html##*/}"
+	rm -f $htmPage
+	cp $dataDir/usage.htm1 $htmPage
 
-	#!@todo fix publishing
 	while IFS=, read PEAKUSAGE_IN MAC IP IFACE PEAKUSAGE_OUT TOTAL FIRSTSEEN LASTSEEN
 	do
 		echo "
 new Array(\"$(lookup $MAC $IP $user_def)\",\"$MAC\",\"$IP\",
 $PEAKUSAGE_IN,$PEAKUSAGE_OUT,$TOTAL,\"$FIRSTSEEN\",\"$LASTSEEN\")," >> ${pb_html}.tmp
-	done < /tmp/sorted_${updatePID}.tmp
-	echo "0);" >> ${pb_html}.tmp
+	done < $tmpDir/sorted_${updatePID}.tmp
+	echo "0);" >> $htmPage
 
-	sed "s/(date)/`date`/" < $dataDir/usage.htm2 >> ${pb_html}.tmp
-	mv ${pb_html}.tmp "$pb_html"
+	sed "s/(date)/`date`/" < $dataDir/usage.htm2 >> $htmPage
+	mv $htmPage "$pb_html"
 }
 
 updatePrepare() {
+	checkDbArg
+	createDbIfMissing
+	checkDB
+	[ -e $tmpDir ] || mkdir -p  $tmpDir
+
 	local timeNow=$(cat /proc/uptime | awk '{print $1}')
 	local timeLast=0
 	if [ -e "$logFile" ]; then
@@ -246,20 +252,14 @@ updatePrepare() {
 	fi
 }
 
-update()
-{
+update() {
 	updatePID=$( sh -c 'echo $PPID' )
 
 	lockFunc
 
-	checkDbArg
-	wan=$(detectWAN)
-	checkWAN
-
+	local wan=$(detectWAN)
+	checkWAN $wan
 	interfaces="$interfaces $wan"
-
-	createDbIfMissing
-	checkDB
 
 	[ "$Monitor46" = 4 ] && IPT='iptables'
 	[ "$Monitor46" = 6 ] && IPT='ip6tables'
@@ -280,32 +280,32 @@ update()
 			done
 		fi
 		# this will add rules for hosts in arp table
-		> /tmp/${ii}_${updatePID}.tmp
+		> $tmpDir/${ii}_${updatePID}.tmp
 
 		for chain in $chains; do
-			$ii -nvxL RRDIPT_$chain -t mangle -Z >> /tmp/${ii}_${updatePID}.tmp
+			$ii -nvxL RRDIPT_$chain -t mangle -Z >> $tmpDir/${ii}_${updatePID}.tmp
 		done
 	done
 
-	[ -f /tmp/iptables_${updatePID}.tmp ] && (
+	[ -f $tmpDir/iptables_${updatePID}.tmp ] && (
 		ipReg=`uci get network.lan.ipaddr | grep -o -e '\([0-9]\+\.\)\{2\}[0-9]\+'`;
 		awk -v mode="$mode" -v interfaces="$interfaces" -v ipReg="$ipReg" -v wanIF="$wan" \
 		-v ipv6="0" -f $binDir/readDB.awk \
 		$DB \
 		/proc/net/arp \
-		/tmp/iptables_${updatePID}.tmp
+		$tmpDir/iptables_${updatePID}.tmp
 	)
 
-	[ -f /tmp/ip6tables_${updatePID}.tmp ] && (
-		echo "This file is geneated by 'ip -6 neigh'" >/tmp/ip6addr_${updatePID}.tmp
-		`ip -6 neigh >>/tmp/ip6addr_${updatePID}.tmp`;
+	[ -f $tmpDir/ip6tables_${updatePID}.tmp ] && (
+		echo "This file is geneated by 'ip -6 neigh'" > $tmpDir/ip6addr_${updatePID}.tmp
+		`ip -6 neigh >> $tmpDir/ip6addr_${updatePID}.tmp`;
 		ipReg=`ip -6 route | grep default | awk '{print $3}' | awk -F: '{print $1}'`;
 
 		awk -v mode="$mode" -v interfaces="$interfaces" -v ipReg="$ipReg" -v wanIF="$wan" \
 		-v ipv6="1" -f $binDir/readDB.awk \
 		"$DB6" \
-		/tmp/ip6addr_${updatePID}.tmp \
-		/tmp/ip6tables_${updatePID}.tmp
+		$tmpDir/ip6addr_${updatePID}.tmp \
+		$tmpDir/ip6tables_${updatePID}.tmp
 	)
 
 	[ "$Monitor46" = 46 ] && (
@@ -316,8 +316,15 @@ update()
 
 	[ -n "$pb_html" ] && publish
 
-	rm -f /tmp/*_${updatePID}.tmp
+	rm -f $tmpDir/*_${updatePID}.tmp
 	unlockFunc
+}
+
+renamefile() {
+	local base=$(basename -- "$1")
+	local ext=$([ -z "${base/*.*/}"  ] && echo ".${base##*.}" || echo '')
+	local base="${base%.*}"
+	echo "$(dirname $1)/${base}$2$ext" && return
 }
 
 ending()
@@ -327,15 +334,14 @@ ending()
 
 	if checkPid $pidFile; then
 		local pid=$( cat $pidFile )
-		rm -f $lockFile $logFile $pidFile /tmp/*_${updatePID}.tmp ${pb_html}.tmp
+		rm -rf $lockFile $logFile $pidFile $tmpDir/*
 		kill -9 $pid >> /dev/null 2>&1
 	fi
 	echo "exit!!"
 }
 
 checkPid() {
-	local pid=""
-	[ -e "$1" ] && pid=$(cat $1) || return 1
+	[ -e "$1" ] && local pid=$(cat $1) || return 1
 	[ -d "/proc/$pid" ] && {
 		[ -n $(echo $(cat "/proc/$pid/cmdline") | grep wrtbwmon ) ]  && return 0
 	}
@@ -390,15 +396,15 @@ Note: [user_file] is an optional file to match users with MAC addresses.
 while [ $# != 0 ];do
 	case $1 in
 		"-k" )
-			ending
+			/etc/init.d/wrtbwmon stop
 			exit 0
 		;;
 		"-f" )
 			shift
 			if [ $# -gt 0 ];then
 				DB=$1
-				DB6=$( echo "${DB%.*}.6.${DB##*.}" )
-				DB46=$( echo "${DB%.*}.46.${DB##*.}" )
+				DB6="$(renamefile $DB .6)"
+				DB46="$(renamefile $DB .46)"
 			else
 				echo "No db file path seted, exit!!"
 				exit 1
